import Link from 'next/link'
import Layout from '../components/Layout.js'

export default function Articles({
  articles
}) {
  return (
    <Layout
      title="Articles"
      description="Generated by create next app"
      >Articles

    </Layout>
  )
}

export async function getStaticProps(ctx) {
  // const response = await fetch(`http://localhost:3000/api/articles`)
  // const articles = await response.json()
  const articles = []
  return {
    props: {
      articles: articles
    }
  }
}
