import Link from 'next/link';
import Layout from '../components/Layout.js';

export default function Articles({ articles }) {
  return (
    <Layout title="Articles" description="Generated by create next app">
      <h1 className='wt-title'>Articles</h1>
      <p className="italic font-bold my-5">This page.</p>
      <ul>
        {articles.map(article => (
          <li key={article.slug} className="my-5">
            <h2 className="font-bold mb-1">
              <Link href={`/articles/${article.articleId}`}>{article.title}</Link>
            </h2>
            <p>{article.message}</p>
          </li>
        ))}
      </ul>
    </Layout>
  );
}

export async function getStaticProps() {
  // Fetch data from your API or database
  const response = await fetch('/api/articles');
  const articles = await response.json();

  return {
    props: {
      articles,
    },
  };
}
