import Link from 'next/link'
import Layout from '../components/Layout.js'
import CardList from "../components/CardList.js";
import Menu from "../components/Menu.js";
import Search from '@/components/Search.js';
import {server} from "../config/config.js"

export default function Articles(props) {
  return (
    <Layout
      title="Articles"
      description="Generated by create next app"
    >
    <Search search={props.search}/>
      <div className="flex gap-[50px]">
        
        <CardList {...props} />
        <Menu />
      </div>

    </Layout>
  )
}


export const getServerSideProps = async (ctx) => {
  const page = parseInt(ctx.query.page) || 1
  const search = ctx.query.search || ""
  const response_articles = await fetch(`${server}/api/articles?search=${search}&page=${page}`)
  const articles = await response_articles.json()

  return {
    props: {
      articles: articles,
      page: page,
      search: search
    }
  }
}
