import Link from 'next/link'
import Layout from '../components/Layout.js'
import { useContext } from 'react';
import UserContext from '../components/UserContext'
import Featured from '../components/featured/Featured.js'
import CategoryList from '../components/categoryList/CategoryList.js'
import CardList from "../components/cardList/CardList.js";
import Menu from "../components/Menu/Menu.js";
import { createPagesServerClient } from '@supabase/auth-helpers-nextjs'


export const getServerSideProps = async (ctx) => {
  // Create authenticated Supabase Client
  const supabase = createPagesServerClient(ctx)
  // Run queries with RLS on the server
  const { data } = await supabase.from('Post').select('*',{ count: 'exact' })
  return {
    props: {
      data: data ?? [],
    },
  }
}

export default function Page(props) {
  return (
    <Layout
      title=""
      description="Generated by create next app"
    >
      <div className="min-h-screen ">
        <Featured />
        <CategoryList />
        <div className="flex gap-[50px]">
          <CardList {...props}/>
          <Menu/>
        </div>
      </div>
    </Layout>
  )
}
