import Link from 'next/link'
import Layout from '../components/Layout.js'
import { useContext } from 'react';
import UserContext from '../components/UserContext'
import Featured from '../components/featured/Featured.js'
import CategoryList from '../components/menuCategories/MenuCategories.js'
import CardList from "../components/cardList/CardList.js";
import Menu from "../components/Menu/Menu.js";

export default function Page(props) {
  const { profile } = useContext(UserContext)
  const page = parseInt(props.page) || 1;
  return (
    <Layout
      title=""
      description="Generated by create next app"
    >
      <Featured />
      <CategoryList />
      <div className="">
        <Menu />
      </div>
    </Layout>
  )
}
