import Link from 'next/link'
import Layout from '../components/Layout.js'
import { useContext } from 'react';
import UserContext from '../components/UserContext'
import Featured from '../components/featured/Featured.js'
import CategoryList from '../components/categoryList/CategoryList.js'
import CardList from "../components/cardList/CardList.js";
import Menu from "../components/Menu/Menu.js";

export default function Page() {
  return (
    <Layout
      title=""
      description="Generated by create next app"
    >
      <div className="min-h-screen ">
        <Featured />
        <CategoryList />
        <div className="flex gap-[50px]">
          <CardList />
          <Menu/>
        </div>
      </div>
    </Layout>
  )
}
